### PR TITLE
Additional policies for build user

### LINKED ISSUE #3: Allow optional bucket read access
Add a new optional variable for a list of buckets that the build user requires read access to.

The bucket access policy should look something like this:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::BUCKET-NAME/*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::BUCKET-NAME"
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": "s3:HeadBucket",
            "Resource": "*"
        }
    ]
}```

### PR DESCRIPTION
**Pull request by dav3r**
# 

## 🗣 Description
This PR adds the ability to specify a list of policy ARNs to be added to the build user role (both in Production and Staging).

Resolves #3.

## 💭 Motivation and Context
We have a need for the build user to be able to read objects from a bucket.  This PR enables that by allowing us to attach custom bucket-access policies (e.g. those created with the new [`s3-read-role-tf-module`](https://github.com/cisagov/s3-read-role-tf-module)) to our build user.

## 🧪 Testing
I created a test user for [`nessus-packer`](https://github.com/cisagov/nessus-packer) and verified that the additional staging bucket-access policy was indeed added to the build user's `EC2AMICreate-test-nessus-packer` role.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by dav3r** [comment]
@jsf9k @felddy @mcdonnnj - Please hold off on reviewing this PR until you hear from me.  I'm going to make some changes, based on the discussion in https://github.com/cisagov/cool-accounts/issues/46.

**Comment by dav3r** [comment]
@jsf9k @felddy @mcdonnnj - This PR is ready to be reviewed at your leisure.

**Review by jsf9k — APPROVED** [review]
Great work!  I can't think of a cleaner way to do this.

**Review by felddy — APPROVED** [review]
Very nice.  🤘

**Pull request merged**
